### ISSUE TITLE
problem with shapes when running gradcam in yolo

### ISSUE THREAD

**Issue by adelshafiei** [wakanawakana/YOLOv2#1]
I am trying your code and getting this error:
>> python3 yolov2_darknet_parser.py yolo.weights
yolov2.conv21.W.data = dat[38718432:67029984].reshape(1024, 3072, 3, 3)
Traceback (most recent call last):
  File "yolov2_darknet_parser.py", line 91, in <module>
    exec(txt)
  File "<string>", line 1, in <module>
ValueError: cannot reshape array of size 12265129 into shape (1024,3072,3,3)

also download_images.py cannot download animal pics.

**Comment by wakanawakana** [comment]
Is chainer 1.16 & python2.7?
It is unknown if the binary works on other versions as the binary structure of the model changes often.

**Comment by wakanawakana** [comment]
Use 'yolov2_gcma.py' if you can read weight files
